name: e_commerce
description: "A Dart-Flutter eCommerce App using GetX State Management & Feature Based MVVM Architecture * Guided Project by UnknownPro."


publish_to: 'https:\\qrdpro.com'

version: 2025.04.09+1

environment:
  sdk: ^3.5.0

  #--------[PACKAGES]------------
dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8

  # UTILITIES
  smooth_page_indicator: ^1.2.0+3
  flutter_native_splash: ^2.4.4
  connectivity_plus: ^6.1.3
  carousel_slider: ^5.0.0
  readmore: ^3.0.0
  iconsax: ^0.0.8
  lottie: ^3.3.1

  # State-Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Firebase
  cloud_firestore: ^5.6.5
  google_sign_in: ^6.3.0
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1

#--------------------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  #--------[ASSETS]------------
  assets:
    - assets/logo/
    - assets/animations/
    - assets/images/
    - assets/icons/categories/
    - assets/icons/payment_methods/
    - assets/banners/
    - assets/products/
    - assets/brands/

  #--------[FONTS]------------
  fonts:
    - family: 'Nunito'
      fonts:
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Italic.ttf
          style: italic
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 800

  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
